## 3255 Final Project Proposal

Link to dataset: https://www.kaggle.com/datasets/keplersmachines/kepler-labelled-time-series-data

I will be conducting **time series analysis** on Kepler labelled time series spacial data. Time series analysis is something that I have not been able to do yet in my data science curriculum, so I wanted to choose something new as a challenge.

The data describe the change in flux (light intensity) of several thousand stars. Each star has a binary label of 2 or 1. 2 indicated that that the star is confirmed to have at least one exoplanet in orbit; some observations are in fact multi-planet systems.

As you can imagine, planets themselves do not emit light, but the stars that they orbit do. If said star is watched over several months or years, there may be a regular 'dimming' of the flux (the light intensity). This is evidence that there may be an orbiting body around the star; such a star could be considered to be a 'candidate' system. Further study of our candidate system, for example by a satellite that captures light at a different wavelength, could solidify the belief that the candidate can in fact be 'confirmed'.

Thus, I will be looking for patterns within the light/time data to find exoplanets in deep space. I have always been interested in space and the ability to combine this interest with my data science skills is very enticing.

### Description of Dataset:
Trainset:

5087 rows or observations.
3198 columns or features.
Column 1 is the label vector. Columns 2 - 3198 are the flux values over time.
37 confirmed exoplanet-stars and 5050 non-exoplanet-stars.

Testset:

570 rows or observations.
3198 columns or features.
Column 1 is the label vector. Columns 2 - 3198 are the flux values over time.
5 confirmed exoplanet-stars and 565 non-exoplanet-stars.

**Essentially**: each datapoint is a representation of the amount of light at a specific point in time.

After conducting my time series analysis, I may create a classification model to predict on the testset, I may cluster certain time series, etc.

It is important to note that I do not know how to do time series analysis nor do I know a lot of about explanet hunting/this type of data, so I see this as partially a research project.